import Head from 'next/head'
import Image from 'next/image'
import Footer from "../components/Footer"
import styles from '../styles/home.module.css'
import classnames from "classnames"

export default function Home() {

  return (
    <div className={styles.container}>
      <Head>
        <title>MarinoCodes</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/branding/MarinoSquareALT.png" />
      </Head>

      <main className={styles.main}>
        <Image draggable={false} className={classnames(styles.logo, styles.online)} src="/branding/MarinoSquareWh.png" alt="Marino Logo" width={150} height={150}></Image>
        {/* eslint-disable-next-line react/no-unescaped-entities*/}
        <h1><span className={styles.lighter}>Hey, I'm</span> Marino</h1>
        <h2 className={[styles.lighter, styles.title].join(" ")}>Backend Developer</h2>
      </main>

      <Footer/>
    </div>
  )
}
